vnf-instances:
  image: registry.sonata-nfv.eu:5000/son-catalogue-repos
  links:
   - mongo
  ports:
    - "4013:4013"
  restart: always

vnf-instances_doc:
  image: registry.sonata-nfv.eu:5000/son-catalogue-repos
  ports:
    - "8808:8808"
  command: [rake,yard]
  command: [yard, server, -B, 0.0.0.0]
  restart: always

mongodata:  
  image: mongo:3.0.4
  volumes:
    - /data/db
  command: --break-mongo

mongo:  
  image: mongo:3.0.4
  volumes_from:
    - mongodata
  ports:
    - "27017:27017"
  command: --smallfiles --rest
  restart: always

mongoexpress:
  image: knickers/mongo-express
  links:
    - mongo:mongo
  ports:
    - "8081:8081"
  restart: always
